# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x17\n\x08\x41\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"\x19\n\tImageData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1e\n\rJsonImageData\x12\r\n\x05image\x18\x01 \x01(\t\"+\n\nImageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\x1f\n\x07Vectors\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x1f\n\x08\x44otReply\x12\x13\n\x0b\x64ot_product\x18\x01 \x01(\x02\x32\x9c\x01\n\tImageMath\x12\x1d\n\x03\x41\x64\x64\x12\x0b.AddRequest\x1a\t.AddReply\x12#\n\x08RawImage\x12\n.ImageData\x1a\x0b.ImageReply\x12!\n\nDotProduct\x12\x08.Vectors\x1a\t.DotReply\x12(\n\tJsonImage\x12\x0e.JsonImageData\x1a\x0b.ImageReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=13
  _globals['_ADDREQUEST']._serialized_end=47
  _globals['_ADDREPLY']._serialized_start=49
  _globals['_ADDREPLY']._serialized_end=72
  _globals['_IMAGEDATA']._serialized_start=74
  _globals['_IMAGEDATA']._serialized_end=99
  _globals['_JSONIMAGEDATA']._serialized_start=101
  _globals['_JSONIMAGEDATA']._serialized_end=131
  _globals['_IMAGEREPLY']._serialized_start=133
  _globals['_IMAGEREPLY']._serialized_end=176
  _globals['_VECTORS']._serialized_start=178
  _globals['_VECTORS']._serialized_end=209
  _globals['_DOTREPLY']._serialized_start=211
  _globals['_DOTREPLY']._serialized_end=242
  _globals['_IMAGEMATH']._serialized_start=245
  _globals['_IMAGEMATH']._serialized_end=401
# @@protoc_insertion_point(module_scope)
